# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_notification_channel(self) -> None:
        """Test case for create_notification_channel

        Create a notification channel
        """
        pass

    def test_create_notification_rule(self) -> None:
        """Test case for create_notification_rule

        Create a notification rule
        """
        pass

    def test_list_notification_channels(self) -> None:
        """Test case for list_notification_channels

        List notification channels
        """
        pass

    def test_list_notification_rules(self) -> None:
        """Test case for list_notification_rules

        List notification rules
        """
        pass

    def test_list_notifications(self) -> None:
        """Test case for list_notifications

        List all alert notifications
        """
        pass


if __name__ == '__main__':
    unittest.main()
