# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.upsert_secrets200_response import UpsertSecrets200Response

class TestUpsertSecrets200Response(unittest.TestCase):
    """UpsertSecrets200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertSecrets200Response:
        """Test UpsertSecrets200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertSecrets200Response`
        """
        model = UpsertSecrets200Response()
        if include_optional:
            return UpsertSecrets200Response(
                success = True,
                count = 56
            )
        else:
            return UpsertSecrets200Response(
        )
        """

    def testUpsertSecrets200Response(self):
        """Test UpsertSecrets200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
