# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.access_api import AccessApi


class TestAccessApi(unittest.TestCase):
    """AccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessApi()

    def tearDown(self) -> None:
        pass

    def test_create_access_request(self) -> None:
        """Test case for create_access_request

        Submit a JIT access request
        """
        pass

    def test_list_access_requests(self) -> None:
        """Test case for list_access_requests

        List JIT access requests
        """
        pass


if __name__ == '__main__':
    unittest.main()
