# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.upsert_secrets409_response import UpsertSecrets409Response

class TestUpsertSecrets409Response(unittest.TestCase):
    """UpsertSecrets409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertSecrets409Response:
        """Test UpsertSecrets409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertSecrets409Response`
        """
        model = UpsertSecrets409Response()
        if include_optional:
            return UpsertSecrets409Response(
                error = '',
                conflicts = [
                    null
                    ]
            )
        else:
            return UpsertSecrets409Response(
        )
        """

    def testUpsertSecrets409Response(self):
        """Test UpsertSecrets409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
