# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_notification_channel_request import CreateNotificationChannelRequest

class TestCreateNotificationChannelRequest(unittest.TestCase):
    """CreateNotificationChannelRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNotificationChannelRequest:
        """Test CreateNotificationChannelRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNotificationChannelRequest`
        """
        model = CreateNotificationChannelRequest()
        if include_optional:
            return CreateNotificationChannelRequest(
                type = 'slack',
                name = 'Slack - Security Alerts',
                config = None
            )
        else:
            return CreateNotificationChannelRequest(
                type = 'slack',
                name = 'Slack - Security Alerts',
                config = None,
        )
        """

    def testCreateNotificationChannelRequest(self):
        """Test CreateNotificationChannelRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
