# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.branches_api import BranchesApi


class TestBranchesApi(unittest.TestCase):
    """BranchesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BranchesApi()

    def tearDown(self) -> None:
        pass

    def test_create_branch(self) -> None:
        """Test case for create_branch

        Create a new branch
        """
        pass

    def test_list_branches(self) -> None:
        """Test case for list_branches

        List branches for a project
        """
        pass


if __name__ == '__main__':
    unittest.main()
