# coding: utf-8

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.audit_api import AuditApi


class TestAuditApi(unittest.TestCase):
    """AuditApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuditApi()

    def tearDown(self) -> None:
        pass

    def test_get_audit_logs(self) -> None:
        """Test case for get_audit_logs

        Get audit logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
