/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpsertSecretsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertSecretsRequest{}

// UpsertSecretsRequest struct for UpsertSecretsRequest
type UpsertSecretsRequest struct {
	Secrets map[string]string `json:"secrets,omitempty"`
	Branch *string `json:"branch,omitempty"`
	// For optimistic locking. Map of key to expected current version.
	ExpectedVersions map[string]string `json:"expectedVersions,omitempty"`
}

// NewUpsertSecretsRequest instantiates a new UpsertSecretsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertSecretsRequest() *UpsertSecretsRequest {
	this := UpsertSecretsRequest{}
	var branch string = "main"
	this.Branch = &branch
	return &this
}

// NewUpsertSecretsRequestWithDefaults instantiates a new UpsertSecretsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertSecretsRequestWithDefaults() *UpsertSecretsRequest {
	this := UpsertSecretsRequest{}
	var branch string = "main"
	this.Branch = &branch
	return &this
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *UpsertSecretsRequest) GetSecrets() map[string]string {
	if o == nil || IsNil(o.Secrets) {
		var ret map[string]string
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecretsRequest) GetSecretsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Secrets) {
		return map[string]string{}, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *UpsertSecretsRequest) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given map[string]string and assigns it to the Secrets field.
func (o *UpsertSecretsRequest) SetSecrets(v map[string]string) {
	o.Secrets = v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *UpsertSecretsRequest) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecretsRequest) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *UpsertSecretsRequest) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *UpsertSecretsRequest) SetBranch(v string) {
	o.Branch = &v
}

// GetExpectedVersions returns the ExpectedVersions field value if set, zero value otherwise.
func (o *UpsertSecretsRequest) GetExpectedVersions() map[string]string {
	if o == nil || IsNil(o.ExpectedVersions) {
		var ret map[string]string
		return ret
	}
	return o.ExpectedVersions
}

// GetExpectedVersionsOk returns a tuple with the ExpectedVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecretsRequest) GetExpectedVersionsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ExpectedVersions) {
		return map[string]string{}, false
	}
	return o.ExpectedVersions, true
}

// HasExpectedVersions returns a boolean if a field has been set.
func (o *UpsertSecretsRequest) HasExpectedVersions() bool {
	if o != nil && !IsNil(o.ExpectedVersions) {
		return true
	}

	return false
}

// SetExpectedVersions gets a reference to the given map[string]string and assigns it to the ExpectedVersions field.
func (o *UpsertSecretsRequest) SetExpectedVersions(v map[string]string) {
	o.ExpectedVersions = v
}

func (o UpsertSecretsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertSecretsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.ExpectedVersions) {
		toSerialize["expectedVersions"] = o.ExpectedVersions
	}
	return toSerialize, nil
}

type NullableUpsertSecretsRequest struct {
	value *UpsertSecretsRequest
	isSet bool
}

func (v NullableUpsertSecretsRequest) Get() *UpsertSecretsRequest {
	return v.value
}

func (v *NullableUpsertSecretsRequest) Set(val *UpsertSecretsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertSecretsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertSecretsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertSecretsRequest(val *UpsertSecretsRequest) *NullableUpsertSecretsRequest {
	return &NullableUpsertSecretsRequest{value: val, isSet: true}
}

func (v NullableUpsertSecretsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertSecretsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


