/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpsertSecrets409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertSecrets409Response{}

// UpsertSecrets409Response struct for UpsertSecrets409Response
type UpsertSecrets409Response struct {
	Error *string `json:"error,omitempty"`
	Conflicts []interface{} `json:"conflicts,omitempty"`
}

// NewUpsertSecrets409Response instantiates a new UpsertSecrets409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertSecrets409Response() *UpsertSecrets409Response {
	this := UpsertSecrets409Response{}
	return &this
}

// NewUpsertSecrets409ResponseWithDefaults instantiates a new UpsertSecrets409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertSecrets409ResponseWithDefaults() *UpsertSecrets409Response {
	this := UpsertSecrets409Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UpsertSecrets409Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecrets409Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UpsertSecrets409Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UpsertSecrets409Response) SetError(v string) {
	o.Error = &v
}

// GetConflicts returns the Conflicts field value if set, zero value otherwise.
func (o *UpsertSecrets409Response) GetConflicts() []interface{} {
	if o == nil || IsNil(o.Conflicts) {
		var ret []interface{}
		return ret
	}
	return o.Conflicts
}

// GetConflictsOk returns a tuple with the Conflicts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecrets409Response) GetConflictsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Conflicts) {
		return nil, false
	}
	return o.Conflicts, true
}

// HasConflicts returns a boolean if a field has been set.
func (o *UpsertSecrets409Response) HasConflicts() bool {
	if o != nil && !IsNil(o.Conflicts) {
		return true
	}

	return false
}

// SetConflicts gets a reference to the given []interface{} and assigns it to the Conflicts field.
func (o *UpsertSecrets409Response) SetConflicts(v []interface{}) {
	o.Conflicts = v
}

func (o UpsertSecrets409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertSecrets409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Conflicts) {
		toSerialize["conflicts"] = o.Conflicts
	}
	return toSerialize, nil
}

type NullableUpsertSecrets409Response struct {
	value *UpsertSecrets409Response
	isSet bool
}

func (v NullableUpsertSecrets409Response) Get() *UpsertSecrets409Response {
	return v.value
}

func (v *NullableUpsertSecrets409Response) Set(val *UpsertSecrets409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertSecrets409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertSecrets409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertSecrets409Response(val *UpsertSecrets409Response) *NullableUpsertSecrets409Response {
	return &NullableUpsertSecrets409Response{value: val, isSet: true}
}

func (v NullableUpsertSecrets409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertSecrets409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


