/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpsertSecrets200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpsertSecrets200Response{}

// UpsertSecrets200Response struct for UpsertSecrets200Response
type UpsertSecrets200Response struct {
	Success *bool `json:"success,omitempty"`
	Count *int32 `json:"count,omitempty"`
}

// NewUpsertSecrets200Response instantiates a new UpsertSecrets200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertSecrets200Response() *UpsertSecrets200Response {
	this := UpsertSecrets200Response{}
	return &this
}

// NewUpsertSecrets200ResponseWithDefaults instantiates a new UpsertSecrets200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertSecrets200ResponseWithDefaults() *UpsertSecrets200Response {
	this := UpsertSecrets200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpsertSecrets200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecrets200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpsertSecrets200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpsertSecrets200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *UpsertSecrets200Response) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpsertSecrets200Response) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *UpsertSecrets200Response) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *UpsertSecrets200Response) SetCount(v int32) {
	o.Count = &v
}

func (o UpsertSecrets200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpsertSecrets200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableUpsertSecrets200Response struct {
	value *UpsertSecrets200Response
	isSet bool
}

func (v NullableUpsertSecrets200Response) Get() *UpsertSecrets200Response {
	return v.value
}

func (v *NullableUpsertSecrets200Response) Set(val *UpsertSecrets200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertSecrets200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertSecrets200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertSecrets200Response(val *UpsertSecrets200Response) *NullableUpsertSecrets200Response {
	return &NullableUpsertSecrets200Response{value: val, isSet: true}
}

func (v NullableUpsertSecrets200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertSecrets200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


