/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBranchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBranchRequest{}

// CreateBranchRequest struct for CreateBranchRequest
type CreateBranchRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	ProjectId string `json:"projectId"`
}

type _CreateBranchRequest CreateBranchRequest

// NewCreateBranchRequest instantiates a new CreateBranchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBranchRequest(name string, projectId string) *CreateBranchRequest {
	this := CreateBranchRequest{}
	this.Name = name
	this.ProjectId = projectId
	return &this
}

// NewCreateBranchRequestWithDefaults instantiates a new CreateBranchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBranchRequestWithDefaults() *CreateBranchRequest {
	this := CreateBranchRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateBranchRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateBranchRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateBranchRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateBranchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBranchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateBranchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateBranchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetProjectId returns the ProjectId field value
func (o *CreateBranchRequest) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *CreateBranchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *CreateBranchRequest) SetProjectId(v string) {
	o.ProjectId = v
}

func (o CreateBranchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBranchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["projectId"] = o.ProjectId
	return toSerialize, nil
}

func (o *CreateBranchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBranchRequest := _CreateBranchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBranchRequest)

	if err != nil {
		return err
	}

	*o = CreateBranchRequest(varCreateBranchRequest)

	return err
}

type NullableCreateBranchRequest struct {
	value *CreateBranchRequest
	isSet bool
}

func (v NullableCreateBranchRequest) Get() *CreateBranchRequest {
	return v.value
}

func (v *NullableCreateBranchRequest) Set(val *CreateBranchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBranchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBranchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBranchRequest(val *CreateBranchRequest) *NullableCreateBranchRequest {
	return &NullableCreateBranchRequest{value: val, isSet: true}
}

func (v NullableCreateBranchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBranchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


