/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNotificationChannelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationChannelRequest{}

// CreateNotificationChannelRequest struct for CreateNotificationChannelRequest
type CreateNotificationChannelRequest struct {
	Type string `json:"type"`
	Name string `json:"name"`
	// Channel-specific config. For Slack: `{ webhookUrl }`. For email: `{ email }`. For webhook: `{ url }`.
	Config map[string]interface{} `json:"config"`
}

type _CreateNotificationChannelRequest CreateNotificationChannelRequest

// NewCreateNotificationChannelRequest instantiates a new CreateNotificationChannelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationChannelRequest(type_ string, name string, config map[string]interface{}) *CreateNotificationChannelRequest {
	this := CreateNotificationChannelRequest{}
	this.Type = type_
	this.Name = name
	this.Config = config
	return &this
}

// NewCreateNotificationChannelRequestWithDefaults instantiates a new CreateNotificationChannelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationChannelRequestWithDefaults() *CreateNotificationChannelRequest {
	this := CreateNotificationChannelRequest{}
	return &this
}

// GetType returns the Type field value
func (o *CreateNotificationChannelRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationChannelRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateNotificationChannelRequest) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value
func (o *CreateNotificationChannelRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationChannelRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateNotificationChannelRequest) SetName(v string) {
	o.Name = v
}

// GetConfig returns the Config field value
func (o *CreateNotificationChannelRequest) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationChannelRequest) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *CreateNotificationChannelRequest) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o CreateNotificationChannelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationChannelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["config"] = o.Config
	return toSerialize, nil
}

func (o *CreateNotificationChannelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"name",
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationChannelRequest := _CreateNotificationChannelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationChannelRequest)

	if err != nil {
		return err
	}

	*o = CreateNotificationChannelRequest(varCreateNotificationChannelRequest)

	return err
}

type NullableCreateNotificationChannelRequest struct {
	value *CreateNotificationChannelRequest
	isSet bool
}

func (v NullableCreateNotificationChannelRequest) Get() *CreateNotificationChannelRequest {
	return v.value
}

func (v *NullableCreateNotificationChannelRequest) Set(val *CreateNotificationChannelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationChannelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationChannelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationChannelRequest(val *CreateNotificationChannelRequest) *NullableCreateNotificationChannelRequest {
	return &NullableCreateNotificationChannelRequest{value: val, isSet: true}
}

func (v NullableCreateNotificationChannelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationChannelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


