/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAccessRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccessRequestRequest{}

// CreateAccessRequestRequest struct for CreateAccessRequestRequest
type CreateAccessRequestRequest struct {
	Reason string `json:"reason"`
	// Duration in minutes
	Duration int32 `json:"duration"`
	SecretId *string `json:"secretId,omitempty"`
	ProjectId *string `json:"projectId,omitempty"`
}

type _CreateAccessRequestRequest CreateAccessRequestRequest

// NewCreateAccessRequestRequest instantiates a new CreateAccessRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccessRequestRequest(reason string, duration int32) *CreateAccessRequestRequest {
	this := CreateAccessRequestRequest{}
	this.Reason = reason
	this.Duration = duration
	return &this
}

// NewCreateAccessRequestRequestWithDefaults instantiates a new CreateAccessRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccessRequestRequestWithDefaults() *CreateAccessRequestRequest {
	this := CreateAccessRequestRequest{}
	return &this
}

// GetReason returns the Reason field value
func (o *CreateAccessRequestRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CreateAccessRequestRequest) SetReason(v string) {
	o.Reason = v
}

// GetDuration returns the Duration field value
func (o *CreateAccessRequestRequest) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestRequest) GetDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *CreateAccessRequestRequest) SetDuration(v int32) {
	o.Duration = v
}

// GetSecretId returns the SecretId field value if set, zero value otherwise.
func (o *CreateAccessRequestRequest) GetSecretId() string {
	if o == nil || IsNil(o.SecretId) {
		var ret string
		return ret
	}
	return *o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestRequest) GetSecretIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecretId) {
		return nil, false
	}
	return o.SecretId, true
}

// HasSecretId returns a boolean if a field has been set.
func (o *CreateAccessRequestRequest) HasSecretId() bool {
	if o != nil && !IsNil(o.SecretId) {
		return true
	}

	return false
}

// SetSecretId gets a reference to the given string and assigns it to the SecretId field.
func (o *CreateAccessRequestRequest) SetSecretId(v string) {
	o.SecretId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CreateAccessRequestRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccessRequestRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreateAccessRequestRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *CreateAccessRequestRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o CreateAccessRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccessRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	toSerialize["duration"] = o.Duration
	if !IsNil(o.SecretId) {
		toSerialize["secretId"] = o.SecretId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	return toSerialize, nil
}

func (o *CreateAccessRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
		"duration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccessRequestRequest := _CreateAccessRequestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAccessRequestRequest)

	if err != nil {
		return err
	}

	*o = CreateAccessRequestRequest(varCreateAccessRequestRequest)

	return err
}

type NullableCreateAccessRequestRequest struct {
	value *CreateAccessRequestRequest
	isSet bool
}

func (v NullableCreateAccessRequestRequest) Get() *CreateAccessRequestRequest {
	return v.value
}

func (v *NullableCreateAccessRequestRequest) Set(val *CreateAccessRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccessRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccessRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccessRequestRequest(val *CreateAccessRequestRequest) *NullableCreateAccessRequestRequest {
	return &NullableCreateAccessRequestRequest{value: val, isSet: true}
}

func (v NullableCreateAccessRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccessRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


