/*
XtraSecurity API

The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNotificationRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationRuleRequest{}

// CreateNotificationRuleRequest struct for CreateNotificationRuleRequest
type CreateNotificationRuleRequest struct {
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Triggers []string `json:"triggers"`
	Channels []string `json:"channels"`
	Conditions map[string]interface{} `json:"conditions,omitempty"`
}

type _CreateNotificationRuleRequest CreateNotificationRuleRequest

// NewCreateNotificationRuleRequest instantiates a new CreateNotificationRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationRuleRequest(name string, triggers []string, channels []string) *CreateNotificationRuleRequest {
	this := CreateNotificationRuleRequest{}
	this.Name = name
	this.Triggers = triggers
	this.Channels = channels
	return &this
}

// NewCreateNotificationRuleRequestWithDefaults instantiates a new CreateNotificationRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationRuleRequestWithDefaults() *CreateNotificationRuleRequest {
	this := CreateNotificationRuleRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateNotificationRuleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateNotificationRuleRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateNotificationRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateNotificationRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateNotificationRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTriggers returns the Triggers field value
func (o *CreateNotificationRuleRequest) GetTriggers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleRequest) GetTriggersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Triggers, true
}

// SetTriggers sets field value
func (o *CreateNotificationRuleRequest) SetTriggers(v []string) {
	o.Triggers = v
}

// GetChannels returns the Channels field value
func (o *CreateNotificationRuleRequest) GetChannels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleRequest) GetChannelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *CreateNotificationRuleRequest) SetChannels(v []string) {
	o.Channels = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *CreateNotificationRuleRequest) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleRequest) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *CreateNotificationRuleRequest) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *CreateNotificationRuleRequest) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

func (o CreateNotificationRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["triggers"] = o.Triggers
	toSerialize["channels"] = o.Channels
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	return toSerialize, nil
}

func (o *CreateNotificationRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"triggers",
		"channels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationRuleRequest := _CreateNotificationRuleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationRuleRequest)

	if err != nil {
		return err
	}

	*o = CreateNotificationRuleRequest(varCreateNotificationRuleRequest)

	return err
}

type NullableCreateNotificationRuleRequest struct {
	value *CreateNotificationRuleRequest
	isSet bool
}

func (v NullableCreateNotificationRuleRequest) Get() *CreateNotificationRuleRequest {
	return v.value
}

func (v *NullableCreateNotificationRuleRequest) Set(val *CreateNotificationRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationRuleRequest(val *CreateNotificationRuleRequest) *NullableCreateNotificationRuleRequest {
	return &NullableCreateNotificationRuleRequest{value: val, isSet: true}
}

func (v NullableCreateNotificationRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


