/* tslint:disable */
/* eslint-disable */
/**
 * XtraSecurity API
 * The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AccessRequest {
    'id'?: string;
    'reason'?: string;
    /**
     * Duration in minutes
     */
    'duration'?: number;
    'status'?: AccessRequestStatusEnum;
    'requestedAt'?: string;
}

export const AccessRequestStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected',
    Expired: 'expired',
    Revoked: 'revoked',
} as const;

export type AccessRequestStatusEnum = typeof AccessRequestStatusEnum[keyof typeof AccessRequestStatusEnum];

export interface AuditLog {
    'id'?: string;
    'action'?: string;
    'entity'?: string;
    'entityId'?: string;
    'changes'?: object;
    'timestamp'?: string;
}
export interface Branch {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'versionNo'?: string;
    'projectId'?: string;
    'createdAt'?: string;
}
export interface CreateAccessRequestRequest {
    'reason': string;
    /**
     * Duration in minutes
     */
    'duration': number;
    'secretId'?: string;
    'projectId'?: string;
}
export interface CreateBranchRequest {
    'name': string;
    'description'?: string;
    'projectId': string;
}
export interface CreateNotificationChannelRequest {
    'type': CreateNotificationChannelRequestTypeEnum;
    'name': string;
    /**
     * Channel-specific config. For Slack: `{ webhookUrl }`. For email: `{ email }`. For webhook: `{ url }`.
     */
    'config': object;
}

export const CreateNotificationChannelRequestTypeEnum = {
    Slack: 'slack',
    Email: 'email',
    Webhook: 'webhook',
    Teams: 'teams',
} as const;

export type CreateNotificationChannelRequestTypeEnum = typeof CreateNotificationChannelRequestTypeEnum[keyof typeof CreateNotificationChannelRequestTypeEnum];

export interface CreateNotificationRuleRequest {
    'name': string;
    'description'?: string;
    'triggers': Array<string>;
    'channels': Array<string>;
    'conditions'?: object;
}
export interface CreateProjectRequest {
    'name': string;
    'description'?: string;
    'workspaceId': string;
}
export interface CreateTeamRequest {
    'name': string;
    'description'?: string;
    'teamColor'?: string;
}
export interface ModelError {
    'error'?: string;
    'message'?: string;
}
export interface Notification {
    'id'?: string;
    'title'?: string;
    'message'?: string;
    'severity'?: NotificationSeverityEnum;
    'type'?: string;
    'read'?: boolean;
    'timestamp'?: string;
}

export const NotificationSeverityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical',
} as const;

export type NotificationSeverityEnum = typeof NotificationSeverityEnum[keyof typeof NotificationSeverityEnum];

export interface NotificationChannel {
    'id'?: string;
    'type'?: NotificationChannelTypeEnum;
    'name'?: string;
    'enabled'?: boolean;
}

export const NotificationChannelTypeEnum = {
    Slack: 'slack',
    Email: 'email',
    Webhook: 'webhook',
    Teams: 'teams',
} as const;

export type NotificationChannelTypeEnum = typeof NotificationChannelTypeEnum[keyof typeof NotificationChannelTypeEnum];

export interface NotificationRule {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'enabled'?: boolean;
    'triggers'?: Array<string>;
    'channels'?: Array<string>;
}
export interface Project {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'status'?: ProjectStatusEnum;
    'accessControl'?: ProjectAccessControlEnum;
    'securityLevel'?: ProjectSecurityLevelEnum;
    'createdAt'?: string;
    'updatedAt'?: string;
}

export const ProjectStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
} as const;

export type ProjectStatusEnum = typeof ProjectStatusEnum[keyof typeof ProjectStatusEnum];
export const ProjectAccessControlEnum = {
    Private: 'private',
    Team: 'team',
    Public: 'public',
} as const;

export type ProjectAccessControlEnum = typeof ProjectAccessControlEnum[keyof typeof ProjectAccessControlEnum];
export const ProjectSecurityLevelEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
} as const;

export type ProjectSecurityLevelEnum = typeof ProjectSecurityLevelEnum[keyof typeof ProjectSecurityLevelEnum];

export interface Secret {
    'key'?: string;
    'value'?: string;
    'version'?: string;
    'isReference'?: boolean;
    'source'?: SecretSourceEnum;
}

export const SecretSourceEnum = {
    Local: 'local',
    Linked: 'linked',
} as const;

export type SecretSourceEnum = typeof SecretSourceEnum[keyof typeof SecretSourceEnum];

export interface Team {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'teamColor'?: string;
    'createdAt'?: string;
}
export interface UpsertSecrets200Response {
    'success'?: boolean;
    'count'?: number;
}
export interface UpsertSecrets409Response {
    'error'?: string;
    'conflicts'?: Array<any>;
}
export interface UpsertSecretsRequest {
    'secrets'?: { [key: string]: string; };
    'branch'?: string;
    /**
     * For optimistic locking. Map of key to expected current version.
     */
    'expectedVersions'?: { [key: string]: string; };
}

/**
 * AccessApi - axios parameter creator
 */
export const AccessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Submit a JIT access request
         * @param {CreateAccessRequestRequest} createAccessRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAccessRequest: async (createAccessRequestRequest: CreateAccessRequestRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAccessRequestRequest' is not null or undefined
            assertParamExists('createAccessRequest', 'createAccessRequestRequest', createAccessRequestRequest)
            const localVarPath = `/access-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAccessRequestRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List JIT access requests
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAccessRequests: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/access-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccessApi - functional programming interface
 */
export const AccessApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccessApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Submit a JIT access request
         * @param {CreateAccessRequestRequest} createAccessRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAccessRequest(createAccessRequestRequest: CreateAccessRequestRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAccessRequest(createAccessRequestRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessApi.createAccessRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List JIT access requests
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAccessRequests(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AccessRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAccessRequests(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessApi.listAccessRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccessApi - factory interface
 */
export const AccessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccessApiFp(configuration)
    return {
        /**
         * 
         * @summary Submit a JIT access request
         * @param {CreateAccessRequestRequest} createAccessRequestRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAccessRequest(createAccessRequestRequest: CreateAccessRequestRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createAccessRequest(createAccessRequestRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List JIT access requests
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAccessRequests(options?: RawAxiosRequestConfig): AxiosPromise<Array<AccessRequest>> {
            return localVarFp.listAccessRequests(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccessApi - object-oriented interface
 */
export class AccessApi extends BaseAPI {
    /**
     * 
     * @summary Submit a JIT access request
     * @param {CreateAccessRequestRequest} createAccessRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createAccessRequest(createAccessRequestRequest: CreateAccessRequestRequest, options?: RawAxiosRequestConfig) {
        return AccessApiFp(this.configuration).createAccessRequest(createAccessRequestRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List JIT access requests
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listAccessRequests(options?: RawAxiosRequestConfig) {
        return AccessApiFp(this.configuration).listAccessRequests(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuditApi - axios parameter creator
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get audit logs
         * @param {string} [workspaceId] 
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogs: async (workspaceId?: string, limit?: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (workspaceId !== undefined) {
                localVarQueryParameter['workspaceId'] = workspaceId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 */
export const AuditApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuditApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get audit logs
         * @param {string} [workspaceId] 
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditLogs(workspaceId?: string, limit?: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AuditLog>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditLogs(workspaceId, limit, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.getAuditLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuditApi - factory interface
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuditApiFp(configuration)
    return {
        /**
         * 
         * @summary Get audit logs
         * @param {string} [workspaceId] 
         * @param {number} [limit] 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogs(workspaceId?: string, limit?: number, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<AuditLog>> {
            return localVarFp.getAuditLogs(workspaceId, limit, page, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - object-oriented interface
 */
export class AuditApi extends BaseAPI {
    /**
     * 
     * @summary Get audit logs
     * @param {string} [workspaceId] 
     * @param {number} [limit] 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAuditLogs(workspaceId?: string, limit?: number, page?: number, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).getAuditLogs(workspaceId, limit, page, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * BranchesApi - axios parameter creator
 */
export const BranchesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new branch
         * @param {CreateBranchRequest} createBranchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBranch: async (createBranchRequest: CreateBranchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createBranchRequest' is not null or undefined
            assertParamExists('createBranch', 'createBranchRequest', createBranchRequest)
            const localVarPath = `/branch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBranchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List branches for a project
         * @param {string} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBranches: async (projectId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('listBranches', 'projectId', projectId)
            const localVarPath = `/branch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (projectId !== undefined) {
                localVarQueryParameter['projectId'] = projectId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BranchesApi - functional programming interface
 */
export const BranchesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BranchesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new branch
         * @param {CreateBranchRequest} createBranchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBranch(createBranchRequest: CreateBranchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBranch(createBranchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchesApi.createBranch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List branches for a project
         * @param {string} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBranches(projectId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Branch>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBranches(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchesApi.listBranches']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BranchesApi - factory interface
 */
export const BranchesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BranchesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new branch
         * @param {CreateBranchRequest} createBranchRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBranch(createBranchRequest: CreateBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createBranch(createBranchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List branches for a project
         * @param {string} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBranches(projectId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Branch>> {
            return localVarFp.listBranches(projectId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BranchesApi - object-oriented interface
 */
export class BranchesApi extends BaseAPI {
    /**
     * 
     * @summary Create a new branch
     * @param {CreateBranchRequest} createBranchRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createBranch(createBranchRequest: CreateBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchesApiFp(this.configuration).createBranch(createBranchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List branches for a project
     * @param {string} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listBranches(projectId: string, options?: RawAxiosRequestConfig) {
        return BranchesApiFp(this.configuration).listBranches(projectId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a notification channel
         * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotificationChannel: async (createNotificationChannelRequest: CreateNotificationChannelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createNotificationChannelRequest' is not null or undefined
            assertParamExists('createNotificationChannel', 'createNotificationChannelRequest', createNotificationChannelRequest)
            const localVarPath = `/notification-channels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createNotificationChannelRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a notification rule
         * @param {CreateNotificationRuleRequest} createNotificationRuleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotificationRule: async (createNotificationRuleRequest: CreateNotificationRuleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createNotificationRuleRequest' is not null or undefined
            assertParamExists('createNotificationRule', 'createNotificationRuleRequest', createNotificationRuleRequest)
            const localVarPath = `/notification-rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createNotificationRuleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List notification channels
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotificationChannels: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notification-channels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List notification rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotificationRules: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notification-rules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all alert notifications
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotifications: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a notification channel
         * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNotificationChannel(createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNotificationChannel(createNotificationChannelRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.createNotificationChannel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a notification rule
         * @param {CreateNotificationRuleRequest} createNotificationRuleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNotificationRule(createNotificationRuleRequest: CreateNotificationRuleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNotificationRule(createNotificationRuleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.createNotificationRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List notification channels
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listNotificationChannels(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NotificationChannel>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listNotificationChannels(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.listNotificationChannels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List notification rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listNotificationRules(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NotificationRule>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listNotificationRules(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.listNotificationRules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all alert notifications
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listNotifications(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Notification>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listNotifications(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.listNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a notification channel
         * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotificationChannel(createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createNotificationChannel(createNotificationChannelRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a notification rule
         * @param {CreateNotificationRuleRequest} createNotificationRuleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotificationRule(createNotificationRuleRequest: CreateNotificationRuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createNotificationRule(createNotificationRuleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List notification channels
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotificationChannels(options?: RawAxiosRequestConfig): AxiosPromise<Array<NotificationChannel>> {
            return localVarFp.listNotificationChannels(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List notification rules
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotificationRules(options?: RawAxiosRequestConfig): AxiosPromise<Array<NotificationRule>> {
            return localVarFp.listNotificationRules(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all alert notifications
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotifications(options?: RawAxiosRequestConfig): AxiosPromise<Array<Notification>> {
            return localVarFp.listNotifications(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi extends BaseAPI {
    /**
     * 
     * @summary Create a notification channel
     * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createNotificationChannel(createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).createNotificationChannel(createNotificationChannelRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a notification rule
     * @param {CreateNotificationRuleRequest} createNotificationRuleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createNotificationRule(createNotificationRuleRequest: CreateNotificationRuleRequest, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).createNotificationRule(createNotificationRuleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List notification channels
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listNotificationChannels(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).listNotificationChannels(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List notification rules
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listNotificationRules(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).listNotificationRules(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all alert notifications
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listNotifications(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).listNotifications(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProjectsApi - axios parameter creator
 */
export const ProjectsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new project
         * @param {CreateProjectRequest} createProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProject: async (createProjectRequest: CreateProjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createProjectRequest' is not null or undefined
            assertParamExists('createProject', 'createProjectRequest', createProjectRequest)
            const localVarPath = `/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all projects the authenticated user has access to.
         * @summary List all projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjects: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectsApi - functional programming interface
 */
export const ProjectsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new project
         * @param {CreateProjectRequest} createProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProject(createProjectRequest: CreateProjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Project>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProject(createProjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.createProject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all projects the authenticated user has access to.
         * @summary List all projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listProjects(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Project>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listProjects(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectsApi.listProjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectsApi - factory interface
 */
export const ProjectsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new project
         * @param {CreateProjectRequest} createProjectRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProject(createProjectRequest: CreateProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<Project> {
            return localVarFp.createProject(createProjectRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all projects the authenticated user has access to.
         * @summary List all projects
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProjects(options?: RawAxiosRequestConfig): AxiosPromise<Array<Project>> {
            return localVarFp.listProjects(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectsApi - object-oriented interface
 */
export class ProjectsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new project
     * @param {CreateProjectRequest} createProjectRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProject(createProjectRequest: CreateProjectRequest, options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).createProject(createProjectRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all projects the authenticated user has access to.
     * @summary List all projects
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listProjects(options?: RawAxiosRequestConfig) {
        return ProjectsApiFp(this.configuration).listProjects(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SecretsApi - axios parameter creator
 */
export const SecretsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns all decrypted key-value pairs for the given project and environment. Requires `secret.read` permission.
         * @summary Get all secrets for an environment
         * @param {string} projectId The project ID
         * @param {GetSecretsEnvEnum} env The environment
         * @param {string} [branch] The branch to read from
         * @param {boolean} [includeVersions] Include version metadata for each secret
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSecrets: async (projectId: string, env: GetSecretsEnvEnum, branch?: string, includeVersions?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('getSecrets', 'projectId', projectId)
            // verify required parameter 'env' is not null or undefined
            assertParamExists('getSecrets', 'env', env)
            const localVarPath = `/projects/{projectId}/envs/{env}/secrets`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"env"}}`, encodeURIComponent(String(env)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (branch !== undefined) {
                localVarQueryParameter['branch'] = branch;
            }

            if (includeVersions !== undefined) {
                localVarQueryParameter['includeVersions'] = includeVersions;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Bulk upsert secrets. Provide a key-value map. Supports optimistic locking via `expectedVersions`.
         * @summary Create or update secrets
         * @param {string} projectId 
         * @param {UpsertSecretsEnvEnum} env 
         * @param {UpsertSecretsRequest} upsertSecretsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertSecrets: async (projectId: string, env: UpsertSecretsEnvEnum, upsertSecretsRequest: UpsertSecretsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('upsertSecrets', 'projectId', projectId)
            // verify required parameter 'env' is not null or undefined
            assertParamExists('upsertSecrets', 'env', env)
            // verify required parameter 'upsertSecretsRequest' is not null or undefined
            assertParamExists('upsertSecrets', 'upsertSecretsRequest', upsertSecretsRequest)
            const localVarPath = `/projects/{projectId}/envs/{env}/secrets`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)))
                .replace(`{${"env"}}`, encodeURIComponent(String(env)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertSecretsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SecretsApi - functional programming interface
 */
export const SecretsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SecretsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns all decrypted key-value pairs for the given project and environment. Requires `secret.read` permission.
         * @summary Get all secrets for an environment
         * @param {string} projectId The project ID
         * @param {GetSecretsEnvEnum} env The environment
         * @param {string} [branch] The branch to read from
         * @param {boolean} [includeVersions] Include version metadata for each secret
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSecrets(projectId: string, env: GetSecretsEnvEnum, branch?: string, includeVersions?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSecrets(projectId, env, branch, includeVersions, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SecretsApi.getSecrets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Bulk upsert secrets. Provide a key-value map. Supports optimistic locking via `expectedVersions`.
         * @summary Create or update secrets
         * @param {string} projectId 
         * @param {UpsertSecretsEnvEnum} env 
         * @param {UpsertSecretsRequest} upsertSecretsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertSecrets(projectId: string, env: UpsertSecretsEnvEnum, upsertSecretsRequest: UpsertSecretsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpsertSecrets200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertSecrets(projectId, env, upsertSecretsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SecretsApi.upsertSecrets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SecretsApi - factory interface
 */
export const SecretsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SecretsApiFp(configuration)
    return {
        /**
         * Returns all decrypted key-value pairs for the given project and environment. Requires `secret.read` permission.
         * @summary Get all secrets for an environment
         * @param {string} projectId The project ID
         * @param {GetSecretsEnvEnum} env The environment
         * @param {string} [branch] The branch to read from
         * @param {boolean} [includeVersions] Include version metadata for each secret
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSecrets(projectId: string, env: GetSecretsEnvEnum, branch?: string, includeVersions?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.getSecrets(projectId, env, branch, includeVersions, options).then((request) => request(axios, basePath));
        },
        /**
         * Bulk upsert secrets. Provide a key-value map. Supports optimistic locking via `expectedVersions`.
         * @summary Create or update secrets
         * @param {string} projectId 
         * @param {UpsertSecretsEnvEnum} env 
         * @param {UpsertSecretsRequest} upsertSecretsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertSecrets(projectId: string, env: UpsertSecretsEnvEnum, upsertSecretsRequest: UpsertSecretsRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpsertSecrets200Response> {
            return localVarFp.upsertSecrets(projectId, env, upsertSecretsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SecretsApi - object-oriented interface
 */
export class SecretsApi extends BaseAPI {
    /**
     * Returns all decrypted key-value pairs for the given project and environment. Requires `secret.read` permission.
     * @summary Get all secrets for an environment
     * @param {string} projectId The project ID
     * @param {GetSecretsEnvEnum} env The environment
     * @param {string} [branch] The branch to read from
     * @param {boolean} [includeVersions] Include version metadata for each secret
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSecrets(projectId: string, env: GetSecretsEnvEnum, branch?: string, includeVersions?: boolean, options?: RawAxiosRequestConfig) {
        return SecretsApiFp(this.configuration).getSecrets(projectId, env, branch, includeVersions, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Bulk upsert secrets. Provide a key-value map. Supports optimistic locking via `expectedVersions`.
     * @summary Create or update secrets
     * @param {string} projectId 
     * @param {UpsertSecretsEnvEnum} env 
     * @param {UpsertSecretsRequest} upsertSecretsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public upsertSecrets(projectId: string, env: UpsertSecretsEnvEnum, upsertSecretsRequest: UpsertSecretsRequest, options?: RawAxiosRequestConfig) {
        return SecretsApiFp(this.configuration).upsertSecrets(projectId, env, upsertSecretsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetSecretsEnvEnum = {
    Development: 'development',
    Staging: 'staging',
    Production: 'production',
} as const;
export type GetSecretsEnvEnum = typeof GetSecretsEnvEnum[keyof typeof GetSecretsEnvEnum];
export const UpsertSecretsEnvEnum = {
    Development: 'development',
    Staging: 'staging',
    Production: 'production',
} as const;
export type UpsertSecretsEnvEnum = typeof UpsertSecretsEnvEnum[keyof typeof UpsertSecretsEnvEnum];


/**
 * TeamsApi - axios parameter creator
 */
export const TeamsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new team
         * @param {CreateTeamRequest} createTeamRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeam: async (createTeamRequest: CreateTeamRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTeamRequest' is not null or undefined
            assertParamExists('createTeam', 'createTeamRequest', createTeamRequest)
            const localVarPath = `/team`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTeamRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTeams: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/team`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeamsApi - functional programming interface
 */
export const TeamsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeamsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new team
         * @param {CreateTeamRequest} createTeamRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTeam(createTeamRequest: CreateTeamRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTeam(createTeamRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamsApi.createTeam']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTeams(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Team>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTeams(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamsApi.listTeams']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TeamsApi - factory interface
 */
export const TeamsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeamsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new team
         * @param {CreateTeamRequest} createTeamRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTeam(createTeamRequest: CreateTeamRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createTeam(createTeamRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all teams
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTeams(options?: RawAxiosRequestConfig): AxiosPromise<Array<Team>> {
            return localVarFp.listTeams(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeamsApi - object-oriented interface
 */
export class TeamsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new team
     * @param {CreateTeamRequest} createTeamRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createTeam(createTeamRequest: CreateTeamRequest, options?: RawAxiosRequestConfig) {
        return TeamsApiFp(this.configuration).createTeam(createTeamRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all teams
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTeams(options?: RawAxiosRequestConfig) {
        return TeamsApiFp(this.configuration).listTeams(options).then((request) => request(this.axios, this.basePath));
    }
}



