# coding: utf-8

# flake8: noqa

"""
    XtraSecurity API

    The XtraSecurity API allows you to programmatically manage secrets, projects, teams, and notifications. Authenticate using Bearer tokens (API Keys) generated from the dashboard.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AccessApi",
    "AuditApi",
    "BranchesApi",
    "NotificationsApi",
    "ProjectsApi",
    "SecretsApi",
    "TeamsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessRequest",
    "AuditLog",
    "Branch",
    "CreateAccessRequestRequest",
    "CreateBranchRequest",
    "CreateNotificationChannelRequest",
    "CreateNotificationRuleRequest",
    "CreateProjectRequest",
    "CreateTeamRequest",
    "Error",
    "Notification",
    "NotificationChannel",
    "NotificationRule",
    "Project",
    "Secret",
    "Team",
    "UpsertSecrets200Response",
    "UpsertSecrets409Response",
    "UpsertSecretsRequest",
]

# import apis into sdk package
from openapi_client.api.access_api import AccessApi as AccessApi
from openapi_client.api.audit_api import AuditApi as AuditApi
from openapi_client.api.branches_api import BranchesApi as BranchesApi
from openapi_client.api.notifications_api import NotificationsApi as NotificationsApi
from openapi_client.api.projects_api import ProjectsApi as ProjectsApi
from openapi_client.api.secrets_api import SecretsApi as SecretsApi
from openapi_client.api.teams_api import TeamsApi as TeamsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.access_request import AccessRequest as AccessRequest
from openapi_client.models.audit_log import AuditLog as AuditLog
from openapi_client.models.branch import Branch as Branch
from openapi_client.models.create_access_request_request import CreateAccessRequestRequest as CreateAccessRequestRequest
from openapi_client.models.create_branch_request import CreateBranchRequest as CreateBranchRequest
from openapi_client.models.create_notification_channel_request import CreateNotificationChannelRequest as CreateNotificationChannelRequest
from openapi_client.models.create_notification_rule_request import CreateNotificationRuleRequest as CreateNotificationRuleRequest
from openapi_client.models.create_project_request import CreateProjectRequest as CreateProjectRequest
from openapi_client.models.create_team_request import CreateTeamRequest as CreateTeamRequest
from openapi_client.models.error import Error as Error
from openapi_client.models.notification import Notification as Notification
from openapi_client.models.notification_channel import NotificationChannel as NotificationChannel
from openapi_client.models.notification_rule import NotificationRule as NotificationRule
from openapi_client.models.project import Project as Project
from openapi_client.models.secret import Secret as Secret
from openapi_client.models.team import Team as Team
from openapi_client.models.upsert_secrets200_response import UpsertSecrets200Response as UpsertSecrets200Response
from openapi_client.models.upsert_secrets409_response import UpsertSecrets409Response as UpsertSecrets409Response
from openapi_client.models.upsert_secrets_request import UpsertSecretsRequest as UpsertSecretsRequest

