/*
XtraSecurity API

Testing SecretsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SecretsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecretsAPIService GetSecrets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var env string

		resp, httpRes, err := apiClient.SecretsAPI.GetSecrets(context.Background(), projectId, env).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsAPIService UpsertSecrets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var env string

		resp, httpRes, err := apiClient.SecretsAPI.UpsertSecrets(context.Background(), projectId, env).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
