import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { verifyAuth } from "@/lib/server-auth";
import { decrypt } from "@/lib/encription";
import axios from "axios";
import jwt from "jsonwebtoken";

async function getGhostCreds(userId: string) {
  const integration = await prisma.integration.findUnique({
    where: { userId_provider: { userId, provider: "ghost" } },
  });
  if (!integration?.accessToken) return null;
  try {
    const adminKey = decrypt(JSON.parse(integration.accessToken));
    const cfg = integration.config as any;
    return { adminKey, url: cfg?.url };
  } catch { return null; }
}

// GET - notification-only
export async function GET() {
  return NextResponse.json({ repos: [] });
}

// POST /api/integrations/ghost/sync - Create Security Log Post
export async function POST(req: NextRequest) {
  try {
    const auth = await verifyAuth(req);
    if (!auth) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { title, message, severity } = await req.json();
    const creds = await getGhostCreds(auth.userId);
    if (!creds) return NextResponse.json({ error: "Ghost not connected" }, { status: 400 });

    const [id, secret] = creds.adminKey.split(":");
    const token = jwt.sign({}, Buffer.from(secret, "hex"), {
      keyid: id, algorithm: "HS256", expiresIn: "5m", audience: `/admin/`
    });

    const body = {
      posts: [{
        title: `[XtraSecurity] ${severity?.toUpperCase()}: ${title}`,
        html: `<p><strong>Severity:</strong> ${severity}</p><p>${message}</p><p><em>Log generated by XtraSecurity Monolith.</em></p>`,
        status: "draft"
      }]
    };

    await axios.post(`${creds.url}/ghost/api/admin/posts/`, body, {
      headers: { "Authorization": `Ghost ${token}`, "Content-Type": "application/json" },
      timeout: 8000,
    });

    return NextResponse.json({ success: true, summary: { total: 1, synced: 1, failed: 0 }, results: [{ key: "ghost_post", success: true }] });
  } catch (error: any) {
    const msg = error.response?.data?.errors?.[0]?.message || error.message;
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
